import { Component } from '@angular/core';
import { AlertController, IonicPage, NavController } from 'ionic-angular';
import { GuestPage } from '../guest/guest';
import { HostSongListPage } from "../host-song-list/host-song-list";
import { HowtoPage } from '../howto/howto';
import { FirebaseProvider } from "../../providers/firebase/firebase";
import { SessionDataProvider } from "../../providers/session-data/session-data";
import { Observable } from "rxjs/Observable";
import { AngularFireDatabase, AngularFireList } from "angularfire2/database";

/**
 * The home page. User can select to be a host or a guest.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-host-guest',
  templateUrl: 'host-guest.html',
})
export class HostGuestPage {
  HostButton: any;
  GuestButton: any;
  HowtoButton: any;
  public roomCode: string;
  // roomList: AngularFireList<any>;
  // rooms: Observable<any[]>;
  roomCodeList: Array<String>;
  found: number = -1;
  ROOMCODE_LENGTH: number = 5;

  constructor(
    public navCtrl: NavController,
    public alertCtrl: AlertController,
    public fBProvider: FirebaseProvider,
    private sDProvider: SessionDataProvider) {
      this.HostButton = HostSongListPage;
      this.GuestButton = GuestPage;
      this.HowtoButton = HowtoPage;
      this.roomCodeList = new Array<String>(2);
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad HostGuestPage');
    console.log('  __  __           _           \n' +
      ' |  \\/  |_   _ ___(_) ___      \n' +
      ' | |\\/| | | | / __| |/ __|     \n' +
      ' | |  | | |_| \\__ \\ | (__      \n' +
      ' |_|  |_|\\__,_|___/_|\\___|     \n' +
      '  __  __                       \n' +
      ' |  \\/  | __ ___   _____ _ __  \n' +
      ' | |\\/| |/ _` \\ \\ / / _ \\ \'_ \\ \n' +
      ' | |  | | (_| |\\ V /  __/ | | |\n' +
      ' |_|  |_|\\__,_| \\_/ \\___|_| |_|\n' +
      '                                       ');
  }

  /**
   * Generate an alphanumeric string of length 5 to be used as a room code.
   * @returns {string}
   */
  genRoomCode() {
    var text = "";
    var possible = "abcdefghijklmnopqrstuvwxyz0123456789";

    //TODO: make the length a constant to avoid hardcoding
    for (var i = 0; i < this.ROOMCODE_LENGTH; i++)
      text += possible.charAt(Math.floor(Math.random() * possible.length));
    return text;
  }

  /**
   * Use the room code generated by genRoomCode() to make a room in the Firebase and then takes
   * the user to the generated room.
   */
  makeRoomAndEnter() {
    this.roomCode = this.genRoomCode();
    this.fBProvider.genRoom(this.roomCode);
    this.sDProvider.roomCode = this.roomCode;
    this.sDProvider.isHost = true;
    let alert = this.alertCtrl.create({
      title: 'Room  "'+this.roomCode+'" Created',
      message: 'Tell your guests this room code! Enjoy the party.',
      buttons: ["OK"]
    });
    alert.present();
    // Set HostSongListPage as root (https://stackoverflow.com/questions/37296999/ionic-2-disabling-back-button-for-a-specific-view)
    this.navCtrl.setRoot(HostSongListPage, {roomCode: this.roomCode}).then(() => {
      this.navCtrl.popToRoot();
    });
  }

}
